import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicFonts = join(root, "public", "fonts");
const stylesFonts = join(root, "src", "app", "styles", "fonts");

const nodeModules = join(root, "node_modules");

const WEIGHTS = [400, 500, 600, 700];
const STYLES = ["normal", "italic"];

const FONT_CONFIG = {
  hanken: {
    variableSubsets: ["latin", "latin-ext", "cyrillic-ext", "vietnamese"],
    staticSubsets: ["latin", "latin-ext", "cyrillic-ext", "vietnamese"],
  },
  jetbrains: {
    variableSubsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
    staticSubsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext"],
  },
};

const sources = {
  hankenVariable: join(nodeModules, "@fontsource-variable/hanken-grotesk", "files"),
  hankenStatic: join(nodeModules, "@fontsource/hanken-grotesk", "files"),
  jetbrainsVariable: join(nodeModules, "@fontsource-variable/jetbrains-mono", "files"),
  jetbrainsStatic: join(nodeModules, "@fontsource/jetbrains-mono", "files"),
  geistSans: join(nodeModules, "geist", "dist", "fonts", "geist-sans"),
  geistMono: join(nodeModules, "geist", "dist", "fonts", "geist-mono"),
};

async function readUnicode(packageName) {
  const raw = await readFile(
    join(nodeModules, packageName, "unicode.json"),
    "utf8",
  );
  return JSON.parse(raw);
}

async function copyFile(from, to) {
  await mkdir(dirname(to), { recursive: true });
  await cp(from, to);
}

function cssBlock({ comment, family, style, weight, weightRange, urls, unicodeRange }) {
  const weightLine = weightRange
    ? `  font-weight: ${weightRange};`
    : `  font-weight: ${weight};`;

  const src = urls
    .map(({ file, format }) => `url("${file}") format("${format}")`)
    .join(",\n    ");

  return `/* ${comment} */
@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-display: swap;
${weightLine}
  src:
    ${src};
  unicode-range: ${unicodeRange};
}
`;
}

function buildVariableFaces({
  family,
  prefix,
  folder,
  unicode,
  subsets,
  includeItalic = true,
}) {
  let css = "";
  for (const subset of subsets) {
    const range = unicode[subset];
    const normalFile = `${prefix}-${subset}-wght-normal.woff2`;
    css += cssBlock({
      comment: `${family} ${subset} variable normal`,
      family,
      style: "normal",
      weightRange: family === "JetBrains Mono" ? "100 800" : "100 900",
      urls: [{ file: `/fonts/${folder}/${normalFile}`, format: "woff2-variations" }],
      unicodeRange: range,
    });

    if (includeItalic) {
      const italicFile = `${prefix}-${subset}-wght-italic.woff2`;
      css += cssBlock({
        comment: `${family} ${subset} variable italic`,
        family,
        style: "italic",
        weightRange: family === "JetBrains Mono" ? "100 800" : "100 900",
        urls: [{ file: `/fonts/${folder}/${italicFile}`, format: "woff2-variations" }],
        unicodeRange: range,
      });
    }
  }
  return css;
}

function buildStaticFaces({ family, prefix, folder, unicode, subsets }) {
  let css = "";
  for (const weight of WEIGHTS) {
    for (const style of STYLES) {
      for (const subset of subsets) {
        const base = `${prefix}-${subset}-${weight}-${style}`;
        css += cssBlock({
          comment: `${family} ${subset} ${weight} ${style} (woff2 + woff fallback)`,
          family,
          style,
          weight,
          urls: [
            { file: `/fonts/${folder}/${base}.woff2`, format: "woff2" },
            { file: `/fonts/${folder}/${base}.woff`, format: "woff" },
          ],
          unicodeRange: unicode[subset],
        });
      }
    }
  }
  return css;
}

async function syncHanken(unicode) {
  const folder = "hanken-grotesk";
  const out = join(publicFonts, folder);
  await mkdir(out, { recursive: true });

  const { variableSubsets, staticSubsets } = FONT_CONFIG.hanken;

  for (const subset of variableSubsets) {
    for (const style of ["normal", "italic"]) {
      const name = `hanken-grotesk-${subset}-wght-${style}.woff2`;
      await copyFile(join(sources.hankenVariable, name), join(out, name));
    }
  }

  for (const weight of WEIGHTS) {
    for (const style of STYLES) {
      for (const subset of staticSubsets) {
        const base = `hanken-grotesk-${subset}-${weight}-${style}`;
        await copyFile(join(sources.hankenStatic, `${base}.woff2`), join(out, `${base}.woff2`));
        await copyFile(join(sources.hankenStatic, `${base}.woff`), join(out, `${base}.woff`));
      }
    }
  }

  const header = `/* Hanken Grotesk — variable (woff2) + static fallbacks (woff2, woff). Generated by scripts/sync-fonts.mjs */\n`;
  const css =
    header +
    buildVariableFaces({
      family: "Hanken Grotesk",
      prefix: "hanken-grotesk",
      folder,
      unicode,
      subsets: variableSubsets,
    }) +
    buildStaticFaces({
      family: "Hanken Grotesk",
      prefix: "hanken-grotesk",
      folder,
      unicode,
      subsets: staticSubsets,
    });

  await writeFile(join(stylesFonts, "hanken-grotesk.css"), css);
}

async function syncJetBrains(unicode) {
  const folder = "jetbrains-mono";
  const out = join(publicFonts, folder);
  await mkdir(out, { recursive: true });

  const { variableSubsets, staticSubsets } = FONT_CONFIG.jetbrains;

  for (const subset of variableSubsets) {
    for (const style of ["normal", "italic"]) {
      const name = `jetbrains-mono-${subset}-wght-${style}.woff2`;
      await copyFile(join(sources.jetbrainsVariable, name), join(out, name));
    }
  }

  for (const weight of WEIGHTS) {
    for (const style of STYLES) {
      for (const subset of staticSubsets) {
        const base = `jetbrains-mono-${subset}-${weight}-${style}`;
        await copyFile(
          join(sources.jetbrainsStatic, `${base}.woff2`),
          join(out, `${base}.woff2`),
        );
        await copyFile(
          join(sources.jetbrainsStatic, `${base}.woff`),
          join(out, `${base}.woff`),
        );
      }
    }
  }

  const header = `/* JetBrains Mono — variable (woff2) + static fallbacks (woff2, woff). Generated by scripts/sync-fonts.mjs */\n`;
  const css =
    header +
    buildVariableFaces({
      family: "JetBrains Mono",
      prefix: "jetbrains-mono",
      folder,
      unicode,
      subsets: variableSubsets,
    }) +
    buildStaticFaces({
      family: "JetBrains Mono",
      prefix: "jetbrains-mono",
      folder,
      unicode,
      subsets: staticSubsets,
    });

  await writeFile(join(stylesFonts, "jetbrains-mono.css"), css);
}

async function syncGeist() {
  const sansFolder = "geist";
  const monoFolder = "geist-mono";
  const sansOut = join(publicFonts, sansFolder);
  const monoOut = join(publicFonts, monoFolder);

  await mkdir(sansOut, { recursive: true });
  await mkdir(monoOut, { recursive: true });

  const sansFiles = [
    ["Geist-Variable.woff2", "Geist-Variable.woff2"],
    ["Geist-Italic[wght].woff2", "Geist-Italic[wght].woff2"],
  ];
  const monoFiles = [["GeistMono-Variable.woff2", "GeistMono-Variable.woff2"]];

  for (const [src, dest] of sansFiles) {
    await copyFile(join(sources.geistSans, src), join(sansOut, dest));
  }
  for (const [src, dest] of monoFiles) {
    await copyFile(join(sources.geistMono, src), join(monoOut, dest));
  }

  const header = `/* Geist — upstream ships woff2 only (no woff in npm package). Generated by scripts/sync-fonts.mjs */\n`;

  const sansCss =
    header +
    cssBlock({
      comment: "Geist Sans variable normal",
      family: "Geist",
      style: "normal",
      weightRange: "100 900",
      urls: [{ file: `/fonts/${sansFolder}/Geist-Variable.woff2`, format: "woff2-variations" }],
      unicodeRange: "U+0000-FFFF",
    }) +
    cssBlock({
      comment: "Geist Sans variable italic",
      family: "Geist",
      style: "italic",
      weightRange: "100 900",
      urls: [
        {
          file: `/fonts/${sansFolder}/Geist-Italic[wght].woff2`,
          format: "woff2-variations",
        },
      ],
      unicodeRange: "U+0000-FFFF",
    });

  const monoCss = cssBlock({
      comment: "Geist Mono variable normal",
      family: "Geist Mono",
      style: "normal",
      weightRange: "100 900",
      urls: [
        { file: `/fonts/${monoFolder}/GeistMono-Variable.woff2`, format: "woff2-variations" },
      ],
      unicodeRange: "U+0000-FFFF",
    });

  await writeFile(join(stylesFonts, "geist.css"), sansCss + monoCss);
}

async function writeFontsIndex() {
  const css = `/* Self-hosted fonts — run npm run fonts:sync after install */
@import "./hanken-grotesk.css";
@import "./jetbrains-mono.css";
@import "./geist.css";
`;
  await writeFile(join(stylesFonts, "index.css"), css);
}

async function main() {
  await rm(publicFonts, { recursive: true, force: true });
  await mkdir(stylesFonts, { recursive: true });

  const hankenUnicode = await readUnicode("@fontsource/hanken-grotesk");
  const jetbrainsUnicode = await readUnicode("@fontsource/jetbrains-mono");

  await syncHanken(hankenUnicode);
  await syncJetBrains(jetbrainsUnicode);
  await syncGeist();
  await writeFontsIndex();

  console.log("Fonts synced to public/fonts and src/app/styles/fonts/");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
